version: "{build}"

environment:
  matrix:
  - nodejs_version: "4"
  - nodejs_version: "5"

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm install

test_script:
  - npm test

cache:
  - jspm_packages -> package.json
  - node_modules -> package.json

build: off
