version: "{build}"

environment:
  matrix:
  - nodejs_version: "0.12"
  - nodejs_version: ""  # latest

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm install

test_script:
  - npm test

cache:
  - bower_components

build: off
